---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tp-website
  region: us-east-1

vpc:
  id: $AWS_VPC
  cidr: "192.168.0.0/16"
  sharedNodeSecurityGroup: $AWS_SG
  subnets:
    public:
      us-east-1a: { id: $AWS_Subnet_01 }
      us-east-1b: { id: $AWS_Subnet_02 }

nodeGroups:
- name: nodegroup-workers
  instanceType: t3.small
  labels: { role: worker }
  desiredCapacity: 1
  availabilityZones: ["us-east-1a", "us-east-1b"]
  ssh: 
    allow: true
    publicKeyName: tp-website