---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tp-website
  region: us-east-1

vpc:
  id: "vpc-07068c6f1bdb0eadf"
  cidr: "192.168.0.0/16"
  sharedNodeSecurityGroup: sg-0163139ef91930981
  subnets:
    public:
      us-east-1a: { id: "subnet-03775b57170bf8cd9" }
      us-east-1b: { id: "subnet-00be28d3aea88d233" }

nodeGroups:
- name: nodegroup-workers
  instanceType: t3.small
  labels: { role: worker }
  desiredCapacity: 1
  availabilityZones: ["us-east-1a", "us-east-1b"]
  ssh: 
    allow: true
    publicKeyName: tp-website