apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: tp-service
      port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
    - name: db-port
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306