version: 2.1

jobs:
  scan_and_build_frontend:
    docker:
      - image: circleci/node:14.17.6
    steps:
      - checkout
      - run:
          name: scan and build
          command: |
            cd frontend 
            npm install --legacy-peer-deps
            npm audit fix
            npm install
      # npm run build
      # run test
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
  
  scan_and_build_backend:
    docker:
      - image: circleci/node:14.17.6
    steps:
      - checkout
      - run:
          name: scan and install dependencies
          command: |
            cd backend
            npm install
            npm audit fix
            npm install
      # run test
      - run:
          name: build and upload docker
          command: |
            cd backend
            dockerpath="wasupont/tp-backend"
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
            docker image tag tp-backend $dockerpath
            echo "Docker ID and Image: $dockerpath"
            docker image push $dockerpath
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  deploy_frontend:
    docker:
      - image: circleci/node:14.17.6
    steps:
      - checkout
      - run:
          name: install ftp client
          command: |
            sudo apt-get install ncftp
      - restore_cache:
          keys: [frontend-build]
      - run: 
          name: build frontend
          command: |
            cd frontend
            npm run build
            ncftpput -R -v -u $FTP_USER -p $FTP_PASSWORD $FTP_URL public_html/tmp/ build/*

  build_backend_docker_image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: install depedencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0\
              awscli==1.11.76
      - restore_cache:
          keys: ['backend-build']
      - run:
          name: build backend image and run
          command: |
            cd backend
            docker build --tag wasupont/tp-backend .
            docker run -d -p 3000:3000 -p 3306:3306 -e ENV=DEBUG wasupont/tp-backend

workflows:
  default:
    jobs:
      - scan_and_build_frontend
      - scan_and_build_backend
      - deploy_frontend:
          requires: [scan_and_build_frontend]
      - build_backend_docker_image:
          requires: [scan_and_build_backend]